#!/bin/bash
# Change directory to the script root directory
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
clang++ -Wno-unused-command-line-argument -Wno-unknown-warning-option -fuse-ld=lld${BUILT_LIBCXX+" --stdlib=libc++"}${BUILT_LIBCXX-" -I/usr/include/aarch64-linux-gnu/c++/5"} -latomic -target aarch64-linux-gnu "-I${DIR}/include" -Dxcb_raw_generic_event_t=xcb_ge_generic_event_t "${@/-static-libstdc++}" -v
