macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

task:
  script: |
    clang++ main.cpp -o main
    ./main || :
    bash -c 'echo "run" && sleep 5 && echo "bt all" && echo "disassemble -b -p" && echo "disassemble -b -f" && echo "cont" && sleep 2 && echo "bt all" && echo "disassemble -b -f" && echo "disassemble -b -C" && sleep 2 && echo "bt all" && echo "disassemble -b -p" && echo "disassemble -b -f" && echo "exit"' | lldb ./main