macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

task:
  script: |
    clang++ main.cpp -o main
    bash -c 'echo "run" && sleep 10 && echo "bt all" && echo "exit"' | lldb ./main