macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

task:
  script: |
    echo "Hello World from macOS!"
    uname -a
    csrutil status
    # cat > main.cpp << EOF
    clang++ main.cpp -o main
    ./main
    # EOF
    #exit 0
    git clone https://github.com/minecraft-linux/mcpelauncher-manifest
    git -C mcpelauncher-manifest submodule update --init --recursive
    git -C mcpelauncher-manifest/mcpelauncher-linker fetch origin refs/heads/m1-dev:m1-dev
    git -C mcpelauncher-manifest/mcpelauncher-linker checkout m1-dev
    git -C mcpelauncher-manifest/mcpelauncher-linker/bionic fetch origin refs/heads/m1-dev-verbose:m1-dev-verbose
    git -C mcpelauncher-manifest/mcpelauncher-linker/bionic checkout m1-dev-verbose
    #curl -LO https://github.com/ChristopherHX/mcpelauncherlegacy/releases/download/0.0.3/libmcpelauncherlegacyarm64-v8a.so
    mkdir -p game/lib/arm64-v8a
    mkdir -p game/assets
    #cp libmcpelauncherlegacyarm64-v8a.so game/lib/arm64-v8a/libminecraftpe.so
    #file libmcpelauncherlegacyarm64-v8a.so
    cp libmyapplication.so game/lib/arm64-v8a/libminecraftpe.so
    git clone https://github.com/openssl/openssl.git -b openssl-3.1
    ssldir="$PWD/ssl"
    cd openssl
    ./config --prefix="$ssldir" --openssldir="$ssldir"
    make -j4
    make install_sw || sudo make install_sw
    cd ..
    cmake -B build -S mcpelauncher-manifest -DCMAKE_BUILD_TYPE=Debug "-DOPENSSL_ROOT_DIR=$ssldir" "-DOPENSSL_CRYPTO_LIBRARY=$ssldir/lib/libcrypto.dylib" -DBUILD_UI=OFF
    cmake --build build --parallel
    ./build/mcpelauncher-client/mcpelauncher-client --help || :
    ./build/mcpelauncher-client/mcpelauncher-client --version || :
    ./build/mcpelauncher-client/mcpelauncher-client -dg game -df || :
