macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

task:
  script: |
    curl -L https://github.com/bombela/backward-cpp/raw/master/backward.hpp --output backward.hpp
    clang++ main.cpp -o main
    ./main || :
    bash -c 'echo "run" && sleep 10 && echo "bt all" && echo "exit"' | lldb ./main