macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:latest

task:
  script: |
    #bash ./get_gh_asset.sh ChristopherHX psychic-octo-engine v0.0.0 1.16.201.01.tar.xz
    #tar xf 1.16.201.01.tar.xz
    #bash ./get_gh_asset.sh ChristopherHX psychic-octo-engine v0.0.0 1.19.70.0-stub.tar.xz
    #tar xf 1.19.70.0-stub.tar.xz
    bash ./get_gh_asset.sh ChristopherHX psychic-octo-engine v0.0.0 1.19.70.02.tar.xz
    tar xf 1.19.70.02.tar.xz
    curl -L https://github.com/ChristopherHX/Buildbot/releases/download/v0.0.4669529706/libEGL.dylib --output libEGL.dylib 
    curl -L https://github.com/ChristopherHX/Buildbot/releases/download/v0.0.4669529706/libGLESv2.dylib --output libGLESv2.dylib
    git clone https://github.com/minecraft-linux/mcpelauncher-manifest -b m1-dev
    git -C mcpelauncher-manifest submodule update --init --recursive
    #git -C mcpelauncher-manifest/mcpelauncher-linker fetch origin refs/heads/m1-dev3:m1-dev
    #git -C mcpelauncher-manifest/mcpelauncher-linker checkout m1-dev
    #git -C mcpelauncher-manifest/mcpelauncher-linker/bionic fetch origin refs/heads/m1-dev5:m1-dev
    #git -C mcpelauncher-manifest/mcpelauncher-linker/bionic checkout m1-dev
    #git -C mcpelauncher-manifest/mcpelauncher-core fetch origin refs/heads/m1-dev:m1-dev
    #git -C mcpelauncher-manifest/mcpelauncher-core checkout m1-dev
    #git -C mcpelauncher-manifest/libc-shim fetch origin refs/heads/m1-dev:m1-dev
    #git -C mcpelauncher-manifest/libc-shim checkout m1-dev
    mkdir -p game/lib/arm64-v8a
    mkdir -p game/assets
    cp libc++_shared.so game/lib/arm64-v8a/libc++_shared.so
    cp libminecraftpe.so game/lib/arm64-v8a/libminecraftpe.so
    git clone https://github.com/openssl/openssl.git -b openssl-3.1
    ssldir="$PWD/ssl"
    cd openssl
    ./config --prefix="$ssldir" --openssldir="$ssldir"
    make -j4
    make install_sw || sudo make install_sw
    cd ..
    cmake -B build -S mcpelauncher-manifest -DCMAKE_BUILD_TYPE=Debug "-DOPENSSL_ROOT_DIR=$ssldir" "-DOPENSSL_CRYPTO_LIBRARY=$ssldir/lib/libcrypto.dylib" -DBUILD_UI=OFF -DCMAKE_CXX_FLAGS=-DDEBUG_TCB_FAULT=1 -DJNIVM_ENABLE_TRACE=ON
    cmake --build build --parallel
    #./build/mcpelauncher-client/mcpelauncher-client --help || :
    #./build/mcpelauncher-client/mcpelauncher-client --version || :
    #./build/mcpelauncher-client/mcpelauncher-client -dg game -df || :
    #./build/mcpelauncher-client/mcpelauncher-client -dg 1.19.70.02 -df || :
    export OPENSSL_armcap=1
    export MCPELAUNCHER_LINKER_VERBOSITY=1
    export LD_LIBRARY_PATH=$PWD
    #bash -c 'echo "run -dg game -df" && sleep 10 && echo "bt all" && echo "exit"' | lldb ./build/mcpelauncher-client/mcpelauncher-client || :
    #bash -c 'echo "run -dg 1.16.201.01 -df" && sleep 10 && echo "bt all" && echo "exit"' | lldb ./build/mcpelauncher-client/mcpelauncher-client || :
    #bash -c 'echo "run -dg 1.19.70.0-stub -df" && sleep 10 && echo "bt all" && echo "exit"' | lldb ./build/mcpelauncher-client/mcpelauncher-client || :
    bash -c 'echo "run -dg 1.19.70.02" && sleep 30 && echo "bt all" && echo "exit"' | lldb ./build/mcpelauncher-client/mcpelauncher-client || :
    #export MCPELAUNCHER_LINKER_COPY_INDIRECT=0
    #bash -c 'echo "run -dg game -df" && sleep 10 && echo "bt all" && echo "exit"' | lldb ./build/mcpelauncher-client/mcpelauncher-client || :
    #bash -c 'echo "run -dg 1.16.201.01 -df" && sleep 10 && echo "bt all" && echo "exit"' | lldb ./build/mcpelauncher-client/mcpelauncher-client || :
  env:
    GITHUB_API_TOKEN: ENCRYPTED[a125837e10055e87275efc839344d69101fc9c86ff8a5726bc07b6f5d2606c4238af25b0d6233e9bc01e44d1a5f1a705]
