runs:
  using: composite
  steps:
  - uses: actions/setup-node@v2
    with:
      node-version: '16'
  - run: |
      console.log(process.version);
      console.log("Hi from node");
    shell: node {0}
