inputs:
  module:
    default: "qtbase"
  major:
    default: "6.3"
  minor:
    default: "0"
  # dest:
  #   default: ${{ github.workspace }}
runs:
  using: composite
  steps:
  - uses: ./.github/download-extract-tar
    with:
      url: https://download.qt.io/${{ (contains(inputs.minor, 'alpha') || contains(inputs.minor, 'beta')) && 'development' || 'official' }}_releases/qt/${{ inputs.major }}/${{ inputs.major }}.${{ inputs.minor }}/submodules/${{ inputs.module }}-everywhere-src-${{ inputs.major }}.${{ inputs.minor }}.tar.xz 
      dest: ${{ inputs.module }}
#${{ inputs.dest }}/