runs:
  using: composite
  steps:
  - uses: ./.github/get-qt-source
  - name: Configure Qt
    run: ./qtbase/configure -prefix /opt/qt6 -- -B build-qtbase -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10
    shell: bash
  - name: Build Qt
    run: cmake --build build-qtbase --parallel
    shell: bash
  - name: Install Qt
    run: cmake --install build-qtbase
    shell: bash
