inputs:
  url:
    description: Url
  format:
    description: Extension xz or gz
    default: xz
  strip-components:
    description: Strip the central directory
    default: 1
  dest:
    description: Destination directory
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
  - run: mkdir -p ${{ inputs.dest }}
    shell: bash
  - run: curl -L ${{ inputs.url }} | tar -x${{ inputs.format == 'xz' && 'J' || inputs.format == 'gz' && 'z' }} --strip-components ${{ inputs.strip-components }} ${{ inputs.dest && format('-C {0}', inputs.dest) }} || curl -L ${{ inputs.url }} | tar -x${{ inputs.format == 'xz' && 'J' || inputs.format == 'gz' && 'z' }} --strip-components ${{ inputs.strip-components }} ${{ inputs.dest && format('-C {0}', inputs.dest) }} || curl -L ${{ inputs.url }} | tar -x${{ inputs.format == 'xz' && 'J' || inputs.format == 'gz' && 'z' }} --strip-components ${{ inputs.strip-components }} ${{ inputs.dest && format('-C {0}', inputs.dest) }}


    shell: bash
