inputs:
  module:
    description: qt module to build
runs:
  using: composite
  steps:
  - uses: ./.github/get-qt-source
      with:
        module: ${{ inputs.module }}
  - name: Configure Qt
    run: /opt/qt6/bin/qt-configure-module -prefix /opt/qt6 ${{ inputs.module }} -- -B build-${{ inputs.module }}
    shell: bash
  - name: Build Qt
    run: cmake --build build-${{ inputs.module }} --parallel
    shell: bash
  - name: Install Qt
    run: cmake --install build-${{ inputs.module }}
    shell: bash
