inputs:
  module:
runs:
  using: composite
  steps:
  - uses: ./github/get-qt-source
      with:
        module: ${{ inputs.module }}
  - name: Configure Qt
    run: /opt/qt6/bin/qt-configure-module -prefix /opt/qt6 -- -B build-${{ inputs.module }}
  - name: Build Qt
    run: cmake --build build-${{ inputs.module }} --parallel
  - name: Install Qt
    run: cmake --install build-${{ inputs.module }}
  