inputs:
  module:
    description: qt module to build
runs:
  using: composite
  steps:
  - uses: ./.github/get-qt-source
    with:
      module: ${{ inputs.module }}
  - name: Configure Qt
    run: /opt/qt6/bin/qt-configure-module ${{ inputs.module }} -- -B build-${{ inputs.module }} -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
    shell: bash
  - name: Build Qt
    run: cmake --build build-${{ inputs.module }} --parallel
    shell: bash
  - name: Install Qt
    run: sudo cmake --install build-${{ inputs.module }}
    shell: bash
