on:
  workflow_call:
    inputs:
      MATRIX:
        required: true
        type: string
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: Dump inputs.MATRIX
      run: ${{ inputs.MATRIX }}
      shell: cat {0}
    - name: Dump inputs.MATRIX
      run: ${{ toJson(needs) }}
      shell: cat {0}