name: build-qt6
on: push
jobs:
  buildqt6:
    if: 'false'
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
    - uses: actions/checkout@v2
    - name: Update apt index
      run: apt-get update
    - name: Install Dependencies
      run: apt-get install -y python curl git xz-utils libegl1-mesa-dev libinput-dev libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libgl1-mesa-dev libglu1-mesa-dev libgles2-mesa-dev libxrender-dev unzip bison build-essential gperf flex libasound2-dev libcups2-dev libdrm-dev libegl1-mesa-dev libnss3-dev libpci-dev libpulse-dev libudev-dev libxtst-dev libdbus-1-dev libxcomposite-dev libxcursor-dev libxrandr-dev libxkbfile-dev
    - uses: ./.github/download-extract-tar
      with:
        url: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        dest: /opt/llvm
    - uses: ./.github/download-extract-tar
      with:
        url: https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz
        format: gz
        dest: /opt/cmake
    - name: Install ninja
      run: |
        curl -L -O https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
        mkdir -p /opt/ninja
        unzip ninja-linux -d /opt/ninja
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/github-script@v4
      with:
        github-token: which?
        script: |
          var path = require('path');
          core.addPath('/opt/llvm/bin');
          core.addPath('/opt/cmake/bin');
          core.addPath('/opt/ninja');
          core.addPath(path.join(process.cwd(), '.github/helper'));
          core.exportVariable('CC', 'wclang');
          core.exportVariable('CXX', 'wclang++');
          core.exportVariable('LD_LIBRARY_PATH', '/opt/llvm/lib');
    - uses: ./.github/build-qtbase
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtshadertools
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtdeclarative
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools-qtdeclarative
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtwebchannel
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtsvg
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel-qtsvg
        path: /opt/qt6.tar.xz
  buildqt6-webengine:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    #needs: buildqt6
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-qt6
        workflow_conclusion: 'completed'
        commit: e85a44dcf8c06b7cb006a37d7a62b7998c5437bf
        #run_number: 20
        #branch: qt6
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel-qtsvg
    - run: mkdir -p /opt/qt6 && tar -xJf $PWD/qt6.tar.xz -C /opt/qt6
    - uses: actions/checkout@v2
    - name: Update apt index
      run: apt-get update
    - name: Install Dependencies
      run: apt-get install -y python curl git xz-utils libegl1-mesa-dev libinput-dev libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libgl1-mesa-dev libglu1-mesa-dev libgles2-mesa-dev libxrender-dev unzip bison build-essential gperf flex libasound2-dev libcups2-dev libdrm-dev libegl1-mesa-dev libnss3-dev libpci-dev libpulse-dev libudev-dev libxtst-dev libdbus-1-dev libxcomposite-dev libxcursor-dev libxrandr-dev libxkbfile-dev
    - uses: ./.github/download-extract-tar
      with:
        url: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        dest: /opt/llvm
    - uses: ./.github/download-extract-tar
      with:
        url: https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz
        format: gz
        dest: /opt/cmake
    - name: Install ninja
      run: |
        curl -L -O https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
        mkdir -p /opt/ninja
        unzip ninja-linux -d /opt/ninja
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/github-script@v4
      with:
        github-token: which?
        script: |
          var path = require('path');
          core.addPath('/opt/llvm/bin');
          core.addPath('/opt/cmake/bin');
          core.addPath('/opt/ninja');
          core.addPath(path.join(process.cwd(), '.github/helper'));
          core.exportVariable('CC', 'wclang');
          core.exportVariable('CXX', 'wclang++');
          core.exportVariable('LD_LIBRARY_PATH', '/opt/llvm/lib');
    - uses: ./.github/build-qtmodule
      with:
        module: qtwebengine
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel-qtsvg-qtwebengine
        path: /opt/qt6.tar.xz
