name: build-qt6
on:
  push:
  workflow_dispatch:
    inputs:
      skip:
        type: boolean
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
jobs:
  qtbase:
    if: "!inputs.skip"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: ./.github/build-qtbase
    - run: sudo tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v3
      with:
        name: qtbase
        path: /opt/qt6.tar.xz
  qtshadertools:
    if: "!(cancelled() || failure())"
    needs: qtbase
    uses: ./.github/workflows/build-module.yml
    with:
      CacheSource: qtbase
      Module: qtshadertools
      CacheNumber: "1"
  qtdeclarative:
    if: "!(cancelled() || failure())"
    needs: qtshadertools
    uses: ./.github/workflows/build-module.yml
    with:
      CacheSource: qtbase-qtshadertools
      Module: qtdeclarative
      CacheNumber: "1"
  qtwebchannel:
    if: "!(cancelled() || failure())"
    needs: qtdeclarative
    uses: ./.github/workflows/build-module.yml
    with:
      CacheSource: qtbase-qtshadertools-qtdeclarative
      Module: qtwebchannel
      CacheNumber: "1"
  qtsvg:
    if: "!(cancelled() || failure())"
    needs: qtwebchannel
    uses: ./.github/workflows/build-module.yml
    with:
      CacheSource: qtbase-qtshadertools-qtdeclarative-qtwebchannel
      Module: qtsvg
      CacheNumber: "1"
  qtwebengine:
    if: "!(cancelled() || failure())"
    strategy:
      matrix:
        _:
        - 0
        - 1
        - 2
        - 3
      max-parallel: 1
    needs: qtsvg
    uses: ./.github/workflows/build-module.yml
    with:
      CacheSource: qtbase-qtshadertools-qtdeclarative-qtwebchannel-qtsvg
      Module: qtwebengine
      CacheNumber: "1"