name: build-qt6
on: push
jobs:
  buildqt6:
´    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: ./.github/build-qtbase
    - run: sudo tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v3
      with:
        name: qtbase
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtshadertools
    - run: sudo tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v3
      with:
        name: qtbase-qtshadertools
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtdeclarative
    - run: sudo tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v3
      with:
        name: qtbase-qtshadertools-qtdeclarative
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtwebchannel
    - run: sudo tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v3
      with:
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtsvg
    - run: sudo tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v3
      with:
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel-qtsvg
        path: /opt/qt6.tar.xz
  buildqt6-webengine1:
    needs: buildqt6
    uses: ./.github/workflows/build-webengine.yml
    with:
      CacheNumber: "1"
  buildqt6-webengine2:
    needs: buildqt6-webengine1
    uses: ./.github/workflows/build-webengine.yml
    with:
      CacheNumber: "2"
  buildqt6-webengine3:
    needs: buildqt6-webengine2
    uses: ./.github/workflows/build-webengine.yml
    with:
      CacheNumber: "3"
  buildqt6-webengine4:
    needs: buildqt6-webengine3
    uses: ./.github/workflows/build-webengine.yml
    with:
      CacheNumber: "4"
