name: build-qt6
on: push
jobs:
  buildqt6:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        # See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
        # newer versions of the distribution.
        deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ xenial main restricted
        # deb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted

        ## Major bug fix updates produced after the final release of the
        ## distribution.
        deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted
        # deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted

        ## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
        ## team. Also, please note that software in universe WILL NOT receive any
        ## review or updates from the Ubuntu security team.
        deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ xenial universe
        # deb-src http://archive.ubuntu.com/ubuntu/ xenial universe
        deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ xenial-updates universe
        # deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates universe

        ## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
        ## team, and may not be under a free licence. Please satisfy yourself as to
        ## your rights to use the software. Also, please note that software in
        ## multiverse WILL NOT receive any review or updates from the Ubuntu
        ## security team.
        deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ xenial multiverse
        # deb-src http://archive.ubuntu.com/ubuntu/ xenial multiverse
        deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse
        # deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse

        ## N.B. software from this repository may not have been tested as
        ## extensively as that contained in the main release, although it includes
        ## newer versions of some applications which may provide useful features.
        ## Also, please note that software in backports WILL NOT receive any review
        ## or updates from the Ubuntu security team.
        deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
        # deb-src http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

        ## Uncomment the following two lines to add software from Canonical's
        ## 'partner' repository.
        ## This software is not part of Ubuntu, but is offered by Canonical and the
        ## respective vendors as a service to Ubuntu users.
        # deb [arch=amd64,i386] http://archive.canonical.com/ubuntu xenial partner
        # deb-src http://archive.canonical.com/ubuntu xenial partner

        deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ xenial-security main restricted
        # deb-src http://security.ubuntu.com/ubuntu/ xenial-security main restricted
        deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ xenial-security universe
        # deb-src http://security.ubuntu.com/ubuntu/ xenial-security universe
        deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ xenial-security multiverse
        # deb-src http://security.ubuntu.com/ubuntu/ xenial-security multiverse

        deb [arch=arm64,armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial main universe multiverse restricted
        deb [arch=arm64,armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main universe multiverse restricted
        deb [arch=arm64,armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial-security main universe multiverse restricted
      shell: cp {0} /etc/apt/sources.list
    - name: Update apt index
      run: dpkg --add-architecture arm64 && apt-get update
    - name: Install Dependencies
      run: apt-get install -y docker.io python curl git xz-utils g++-aarch64-linux-gnu libegl1-mesa-dev:arm64 libinput-dev:arm64 libfontconfig1-dev:arm64 libfreetype6-dev:arm64 libx11-dev:arm64 libx11-xcb-dev:arm64 libxext-dev:arm64 libxfixes-dev:arm64 libxi-dev:arm64 libxrender-dev:arm64 libxcb1-dev:arm64 libxcb-glx0-dev:arm64 libxcb-keysyms1-dev:arm64 libxcb-image0-dev:arm64 libxcb-shm0-dev:arm64 libxcb-icccm4-dev:arm64 libxcb-sync-dev:arm64 libxcb-xfixes0-dev:arm64 libxcb-shape0-dev:arm64 libxcb-randr0-dev:arm64 libxcb-render-util0-dev:arm64 libxcb-util-dev:arm64 libxcb-xinerama0-dev:arm64 libxcb-xkb-dev:arm64 libxkbcommon-dev:arm64 libxkbcommon-x11-dev:arm64 libgl1-mesa-dev:arm64 libglu1-mesa-dev:arm64 libgles2-mesa-dev:arm64 libxrender-dev:arm64 unzip bison build-essential gperf flex libasound2-dev:arm64 libcups2-dev:arm64 libdrm-dev:arm64 libegl1-mesa-dev:arm64 libnss3-dev:arm64 libpci-dev:arm64 libpulse-dev:arm64 libudev-dev:arm64 libxtst-dev:arm64 libdbus-1-dev:arm64 libxcomposite-dev:arm64 libxcursor-dev:arm64 libxrandr-dev:arm64 libxkbfile-dev:arm64
    - uses: ./.github/download-extract-tar
      with:
        url: https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang+llvm-12.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
        dest: /opt/llvm
    - uses: ./.github/download-extract-tar
      with:
        url: https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-linux-x86_64.tar.gz
        format: gz
        dest: /opt/cmake
    - name: Install ninja
      run: |
        curl -L -O https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
        mkdir -p /opt/ninja
        unzip ninja-linux -d /opt/ninja
    - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - uses: actions/github-script@v4
      with:
        github-token: which?
        script: |
          var path = require('path');
          core.addPath('/opt/llvm/bin');
          core.addPath('/opt/cmake/bin');
          core.addPath('/opt/ninja');
          core.addPath(path.join(process.cwd(), '.github/helper'));
          core.exportVariable('CC', 'wclang-arm64-linux');
          core.exportVariable('CXX', 'wclang++-arm64-linux');
          core.exportVariable('LD_LIBRARY_PATH', '/opt/llvm/lib');
    - run: |
        git clone https://github.com/llvm/llvm-project.git llvm -b release/12.x --depth 1
        mkdir -p libcxx64-build
        cd libcxx64-build
        cmake ../llvm/llvm -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_LIBCXX=ON
        make -j8 cxx cxxabi
        make install
    - run: tar -cJf /opt/libcxx64.tar.xz -C libcxx64-build .
    - uses: actions/upload-artifact@v2
      with:
        name: libcxx64
        path: /opt/libcxx64.tar.xz
    - run: |
        git clone -b OpenSSL_1_1_1-stable https://github.com/openssl/openssl --depth 1
        cd openssl
        ./Configure linux-aarch64
        make -j8
        make install
    - run: tar -cJf /opt/openssl.tar.xz -C openssl .
    - uses: actions/upload-artifact@v2
      with:
        name: openssl
        path: /opt/openssl.tar.xz
    - uses: actions/github-script@v4
      with:
        github-token: which?
        script: core.exportVariable('BUILT_LIBCXX', 'true');
    - uses: ./.github/build-qtbase
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtshadertools
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtdeclarative
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools-qtdeclarative
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtwebchannel
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtsvg
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel-qtsvg
        path: /opt/qt6.tar.xz
    - uses: ./.github/build-qtmodule
      with:
        module: qtwebengine
    - run: tar -cJf /opt/qt6.tar.xz -C /opt/qt6 .
    - uses: actions/upload-artifact@v2
      with:
        name: qtbase-qtshadertools-qtdeclarative-qtwebchannel-qtsvg-qtwebengine
        path: /opt/qt6.tar.xz
