on: push
jobs:
  comp:
    name: comp-${{toJSON(strategy)}}
    uses: ChristopherHX/newcomposite-sample/.github/workflows/weirdworkflow.yml@reusable-workflows
  after:
    needs: comp
    runs-on: self-hosted
    steps:
    - run: echo '${{toJSON(github)}}'
    - run: echo '${{toJSON(needs)}}'
