on: push
jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/comp1
      with:
        justaSecret: ${{secrets.GITHUB_TOKEN}}
      env:
        justaSecret: ${{secrets.GITHUB_TOKEN}}

  comp:
#     if: 'false'
    name: comp-${{toJSON(strategy)}}
    uses: ChristopherHX/newcomposite-sample/.github/workflows/weirdworkflow.yml@reuse-3
  after:
    needs: comp
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{toJSON(github)}}'
    - run: echo '${{toJSON(needs)}}'
