on: push
jobs:
  sec_inherit:
    uses: ./.github/workflows/sandbox.yml
    secrets: inherit
  sec_removed:
    uses: ./.github/workflows/sandbox.yml
  sec_removed2:
    uses: ./.github/workflows/sandbox.yml
    secrets: {}