on:
  push:
jobs:
  call_plain:
    uses: ./.github/workflows/child.yml
    with:
      MATRIX: ${{ toJson(matrix) }}
  call_matrix:
    uses: ./.github/workflows/child.yml
    strategy:
      matrix:
        v:
          - 0
          - 1
          - 2
          - 3
    with:
      MATRIX: ${{ toJson(matrix) }}
    