on: push
jobs:
  comp:
    runs-on: ubuntu-latest
    steps:
    - uses: ChristopherHX/newcomposite-sample@meta
    - uses: actions/checkout@v2
      with:
        path: testa
    - uses: ./testa/.github/comp1
