on: push
jobs:
  comp:
    strategy:
      matrix:
        l:
        - ubuntu-latest
        - self-hosted
    runs-on: ${{ matrix.l }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/comp1
    - uses: ./.github/comp1
    - uses: ./.github/comp1
