on: push
jobs:
  comp:
    name: comp-${{toJSON(strategy)}}
    uses: ChristopherHX/newcomposite-sample/.github/workflows/weirdworkflow.yml@othertest
    secrets:
      nosecret: ${{secrets.GITHUB_TOKEN}}
  after:
    needs: comp
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{toJSON(github)}}'
    - run: echo '${{toJSON(needs)}}'
