on:
  workflow_dispatch:
    inputs:
      SHA:
        type: string
run-name: Deploy ${{ inputs.environment }} - ${{ inputs.SHA || github.sha }}
jobs:
  comp:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        path: testa
    - uses: ./testa/.github/comp1
