on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ChristopherHX/oidc@main
      id: oidc
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        path: .github/actions
        repository: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
        ref: ${{ steps.oidc.outputs.job_workflow_repo_ref }}
    - run: ls
    - uses: ./.github/actions/dowork
