on:
  workflow_call:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: string
    secrets:
      ENVIRONMENT_SECRET:
        required: true
jobs:
  job_with_environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT_NAME }}
    steps:
    - name: Dump Secret
      run: echo ${{ secrets.ENVIRONMENT_SECRET }}