on:
  workflow_call:
    secrets:
      secret1:
        description: "secret1"
        required: false
      secret2:
        description: "secret2"
        required: false
jobs:
  _:
    runs-on: ubuntu-latest
    steps:
    - run: echo "eyJ0eXAiOif{e"
    - run: echo $SEC
      env:
        SEC: ${{ tojson(secrets) }}
